# Generated by Django 4.2.11 on 2024-04-08 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question",
            old_name="Publication Date",
            new_name="date published",
        ),
    ]
