# Generated by Django 4.2.11 on 2024-04-08 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_rename_publication_date_question_date_published"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question",
            old_name="date published",
            new_name="pub_date",
        ),
    ]
